# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: venice 0.4.0 ruby lib

Gem::Specification.new do |s|
  s.name = "venice"
  s.version = "0.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Mattt Thompson"]
  s.date = "2016-11-30"
  s.description = ""
  s.email = "m@mattt.me"
  s.executables = ["iap"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".rspec",
    "Gemfile",
    "LICENSE",
    "README.md",
    "Rakefile",
    "bin/iap",
    "lib/venice.rb",
    "lib/venice/client.rb",
    "lib/venice/in_app_receipt.rb",
    "lib/venice/receipt.rb",
    "lib/venice/verification_error.rb",
    "lib/venice/version.rb",
    "spec/client_spec.rb",
    "spec/in_app_receipt_spec.rb",
    "spec/receipt",
    "spec/receipt_spec.rb",
    "spec/spec_helper.rb",
    "venice.gemspec"
  ]
  s.homepage = "http://nomad-cli.com"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.8"
  s.summary = "iTunes In-App Purchase Receipt Verification"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<commander>, ["~> 4.1"])
      s.add_runtime_dependency(%q<terminal-table>, ["~> 1.4"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.1"])
    else
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<commander>, ["~> 4.1"])
      s.add_dependency(%q<terminal-table>, ["~> 1.4"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.1"])
    end
  else
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<commander>, ["~> 4.1"])
    s.add_dependency(%q<terminal-table>, ["~> 1.4"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.1"])
  end
end

